language: python
python:
    - "2.7"
    - "3.5"
    - "3.6"
install:
  - pip install --user -r requirements.txt
  - git clone https://github.com/ocsigen/html_of_wiki && make -C html_of_wiki ohow
script:
  - pytest
  - ./mkdoc.sh
deploy:
  provider: pages
  keep-history: true
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  local-dir: _doc
  on:
    branch: master
