language: python

python:
    - "2.7"
    - "3.5"
    - "3.6"

addons:
  apt:
    packages:
      - opam
      - ocaml

install:
  - pip install -r requirements.txt
  - eval $(opam config env)
  - opam init -y
  - opam switch 4.06.1
  - opam install lwt.unix
  - opam install lwt.ppx
  - opam install re.pcre
  - opam install tyxml
  - opam install cmdliner
  - opam install yojson
  - opam install fileutils
  - opam install uri
  - opam install js_of_ocaml.ppx
  - opam install js_of_ocaml-ppx_deriving_json
  - opam install ppx_blob
  - opam install ppx_deriving.std
  - opam install reason
  - opam install str
  - ./install_ohow.sh

script:
  - pytest
  - ./mkdoc.sh

deploy:
  provider: pages
  keep-history: true
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  local-dir: _doc
  on:
    branch: master
