language: c

env:
    - OCAML_VERSION=4.03 PACKAGE=ocsigenserver
    - OCAML_VERSION=4.05 PACKAGE=ocsigenserver
    - OCAML_VERSION=4.06 PACKAGE=ocsigenserver

os:
    - linux
    - osx

jobs:
    include:
        - stage: unit tests
          install: 'echo install UT1'
          script: 'echo UT1'
        - stage: unit tests
          install: 'echo install UT2'
          script: 'echo UT2'
        - stage: deploy to gh pages
          script:
              - ./mkdoc.sh
              - rm -rf _build __pycache__ # some cleanup
          deploy:
              provider: pages
              keep-history: true
              skip-cleanup: true
              github-token: $GITHUB_TOKEN
              local-dir: _doc
              on:
                branch: master
