language: python

python:
    - "2.7"
    - "3.5"
    - "3.6"

before_install:
  - sudo apt-get update
  - sudo apt-get install -y opam m4

install:
  - pip install -r requirements.txt
  - opam init -y
  - eval $(opam config env)
  - git clone https://github.com/ocsigen/html_of_wiki/
  - cd html_of_wiki
  - git checkout opam-install
  - cd ..
  - opam pin add -y html_of_wiki

script:
  - pytest
  - ./mkdoc.sh

deploy:
  provider: pages
  keep-history: true
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  local-dir: _doc
  on:
    branch: master
