language: python

python:
    - "2.7"
    - "3.5"
    - "3.6"

env:
    - OCAML_VERSION=4.06

install:
  - pip install -r requirements.txt

script:
  - pytest
  - ./mkdoc.sh
  - rm -rf _build __pycache__ # some cleanup

deploy:
  provider: pages
  keep-history: true
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  local-dir: _doc
  on:
    branch: master
